[general]
URL = "https://fontique.streamlit.app/"

[firebase]
apiKey = "AIzaSyC3v-XZ67A2K6ANHP9lrwk0Rnt15imWr50"
authDomain = "fontiquee.firebaseapp.com"
projectId = "fontiquee"
databaseURL = "https://fontiquee-default-rtdb.firebaseio.com/"
storageBucket = "fontiquee.appspot.com"
messagingSenderId = "40632878954"
appId = "1:40632878954:web:bbc03aa2e951e1cf17c713"
measurementId = "G-9W51E8CVJ8"

[firebase_admin]
type = "service_account"
project_id = "fontiquee"
private_key_id = "ae8ff1a5c5bce6366abc248bd7ac6e2926d809ed"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQD0n0F1bIBFrIqR\nmZ92hlM9ICREOqoIsLgz2jhWQD51FsUB6qeD7tjuMJwhXALSn5xssEqWgMFOfnat\n5WdNi4119lMtCCoSGLX64lHksO+2rXAJaEYtoMHgxZ7A2RQpadhl0liDfSNVsezI\nAGJ0u0oBroOIbvw1RgoY1H6EqBTF02k3SfPpT4O3RE4o78E3Zc//Lo+2iiw3r8vF\nxx5dsmjxicRtZ7iUQ6vMNL5nr2I2o2ARtsBMaDj7N9gUUazWQN6HxppnzNWacoFC\nC4kVABZgYZnxBms0IoBuOgan/jvq0WPqoBJDXbQ+cdxccsZfCwctCjn9Xmho6LJf\ndwSRn2urAgMBAAECggEATaHO9dOJv9LapQuCamyFtSPiro6JkLl4s+gAsgqwZ5ti\nyVFteTbPPIRLwGCBetNxoqKuASZ6co0638QqbRcpPTL/wY5SP6z879JsV+35HVnc\ncPfZMbjPXqSI1b3uopf3N5UyRwRrNtKBCRXqKQ6ZFYCLOLy0KLoCEVA6mKH4+bCX\n2NmJT4GOasJ2+N4qOWzwexrxLmJMPtD2VDrMKu/yrMrqaYzBQk8mQKwHBIG2YIkG\n2lH80VJqLWoKlDBHO5huhhfZx8OejBvTrwMZ/S+JoaXpsn8OPMF6D+1Bj7fckjys\nuppSErJl4/GdEpcj7osoPm5hGk18FF50ZCrZ0XyE/QKBgQD/TTk2brmyd8WFo1K9\ntXT0uCZDm6sdx+s8UpbICaUI9pTSs2SHlAmP3cg4yFQVWizWlMwfqSPf7aEEPExf\nu6ZVGZaATMyYdlj7V7mrxidxVmUPAl8lMl+y0+vCp7y6KDv2AAiIIY/8MY+j825/\nWG+bLrObRkqqRG4ZY+LKCEQ2VQKBgQD1So3Ey7gHr1tpZz1/fBFQwACIf8iRKJD3\nlypNFn1NNoEt9YW7fwmJ55CI1zwZc4u/Ae5frnu/sLZLY1l0tuiFxLAgBLFfua5n\ncokLOLvLrfRnCQ7widX4Rx1AxTNEuHtDAVgAIloHjz5pUm8adETxwxbpDPJk4306\nedf2g+MZ/wKBgEPASp6XY9Bo2JJOdXbC4PbQp9bpSM/ubg7kG/+aD6IBTh1cXiFc\nt+zl/myTPT0tYRjRBBqi2FJkzYZCOkJtmgabc8U4nFMZlSOedDeRroX1V3xUNMu6\nQotCkh5mRT9hzgfKmnkF7yAORwBLadeBsJyOGDvsu4PUBSPXzievaerBAoGBAJ21\nvqsOdJd0VujROUgzZAqwOGeLCVDTbUnThp4j3JJ9fdcn6kEgL+jb2yEwifKvSOWZ\nf0NDs0sPelXEXereA2imirs7aTPr9ceLa7OsWYpeoSpyN4nOhaVpS9SuNgV0O8Rc\nI9GKRKphnjYni0nOAdoTnjJfYaYeYhDr8EAOkkDPAoGBAKKK2/IX6iPTFY9nKyBd\nc71m6jV7a36vbzgMe0V046WMkSq//H7yfb0n/T7nKIPO9TISjcbqR2kAlGfilDoe\nXoXfqxp0EwvK6pr/nT4jIxbFgPcVvnU9p0d2yx3mnp9XreTARIiZzcxc+nHG+dOS\nB1i5NNqzFXVFYpCVYb7JBM91\n-----END PRIVATE KEY-----\n"
client_email = "firebase-adminsdk-nbqjr@fontiquee.iam.gserviceaccount.com"
client_id = "106584392063793556915"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-nbqjr%40fontiquee.iam.gserviceaccount.com"

[key]
key = 'AIzaSyDg7RQ15HYHasj0BtiztTma2UiIs9XGSas'